---

- name: "Check if {{ common_swap_file }} exists"
  stat:
    path: "{{ common_swap_file }}"
  register: common_swap_file_exists

- name: Create swap space
  command: "dd if=/dev/zero of={{ common_swap_file }} bs=1M count={{ common_swap_size }}"
  when: common_swap_file_exists.stat.exists == false

- name: Make swap
  command: mkswap {{ common_swap_file }}
  when: common_swap_file_exists.stat.exists == false

- name: Add to fstab
  action: lineinfile dest=/etc/fstab line="{{ common_swap_file }} none swap sw 0 0" state=present

- name: Turn swap on
  command: swapon -a

- name: Set vm.swappines
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: yes

- name: Set vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
    state: present
    reload: yes